version: '3'

services:
  web:
    image: bjoernalbers/faxomat
    ports:
      - "631:631"
      - "80:3000"
    env_file:
     - .env/production/web
     - .env/production/db
    volumes:
      - storage:/opt/faxomat/storage
      - export:/opt/faxomat/export
      - cups_spool:/var/spool/cups
      - cups_cache:/var/cache/cups
      - cups_log:/var/log/cups
      - cups_run:/var/run/cups
      - cups_etc:/etc/cups
  db:
    image: postgres:9.5
    env_file:
      - .env/production/db
    volumes:
      - pgdata:/var/lib/postgresql/data
    command:
      - postgres
      - -c
      - shared_buffers=1GB
      - -c
      - work_mem=64MB
      - -c
      - synchronous_commit=off

volumes:
  pgdata:
  storage:
  export:
  cups_spool:
  cups_cache:
  cups_log:
  cups_run:
  cups_etc:
