version: '3'

services:
  web:
    build: .
    ports:
      - "631:631"
      - "3000:3000"
    env_file:
      - .env/development/web
      - .env/development/db
    volumes:
      - storage:/opt/faxomat/storage
      - export:/opt/faxomat/export
      - .:/opt/faxomat
      - cups_spool:/var/spool/cups
      - cups_cache:/var/cache/cups
      - cups_log:/var/log/cups
      - cups_run:/var/run/cups
      - cups_etc:/etc/cups
  db:
    image: postgres:9.5
    env_file:
      - .env/development/db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  storage:
  export:
  cups_spool:
  cups_cache:
  cups_log:
  cups_run:
  cups_etc:
